name:    dumbtube
version: "0.0.0"

dependencies:

- base >=4.16.0 && <5
- yesod >=1.6 && <1.7
- yesod-core >=1.6 && <1.7
- yesod-auth >=1.6 && <1.7
- yesod-static >=1.6 && <1.7
- yesod-form >=1.6 && <1.8
- classy-prelude >=1.5 && <1.6
- classy-prelude-conduit >=1.5 && <1.6
- classy-prelude-yesod >=1.5 && <1.6
- bytestring >=0.10 && <0.12
- text >=0.11 && <2.0
- persistent >=2.9 && <2.14
- persistent-sqlite >=2.9 && <2.14
- persistent-template >=2.5 && <2.14
- template-haskell
- shakespeare >=2.0 && <2.1
- hjsmin >=0.1 && <0.3
- monad-control >=0.3 && <1.1
- wai-extra >=3.0 && <3.2
- yaml >=0.11 && <0.12
- http-client-tls >=0.3 && <0.4
- http-conduit >=2.3 && <2.4
- directory >=1.1 && <1.4
- warp >=3.0 && <3.4
- data-default
- aeson >=1.4 && <2.1
- conduit >=1.0 && <2.0
- monad-logger >=0.3 && <0.4
- fast-logger >=2.2 && <3.2
- wai-logger >=2.2 && <2.5
- file-embed
- safe
- unordered-containers
- containers
- vector
- time
- case-insensitive
- wai
- foreign-store

- df1
- di-core
- di-df1
- di-handle
- effectful
- effectful-core
- effectful-th
- generic-optics
- optics
- optics-vl
- optics-th
- optparse-applicative
- regex-tdfa
- resourcet-effectful
- resourcet
- sqlite-simple
- text
- time
- unliftio
- ulid
- base >= 4.7 && < 5
- name: base
  mixin:
      - hiding (Prelude)
- name: relude
  mixin:
      - (Relude as Prelude)
      - ""
- http-types
- lucid
- servant
- servant-lucid
- servant-server
- attoparsec
- http-media
- warp
- warp-tls
- mtl
- raw-strings-qq
- string-interpolate
- crypton
- resource-pool
- streaming
- direct-sqlite

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

language: GHC2021
default-extensions:
- TemplateHaskell
- TypeFamilies
- DataKinds
- LambdaCase
- OverloadedLabels
- OverloadedRecordDot
- DuplicateRecordFields
- RecordWildCards
- NamedFieldPuns
- GADTs
- DataKinds
- QuasiQuotes

# The library contains all of our application code. The executable
# defined below is just a thin wrapper.
library:
  source-dirs: src
  include-dirs: c-include
  c-sources:
    - c-source/tss2-shim.c
  extra-libraries:
    - tss2-fapi
  when:
  - condition: (flag(dev)) || (flag(library-only))
    then:
      ghc-options:
      - -Wall
      - -fwarn-tabs
      - -O0
      cpp-options: -DDEVELOPMENT
    else:
      ghc-options:
      - -Wall
      - -fwarn-tabs
      - -O2

# Runnable executable for our application
executables:
  dumbtube:
    main: main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - dumbtube
    when:
    - condition: flag(library-only)
      buildable: false

# Test suite
tests:
  dumbtube-test:
    main: Spec.hs
    source-dirs: test
    ghc-options: -Wall
    dependencies:
    - dumbtube
    - hspec >=2.0.0
    - yesod-test
    - microlens

# Define flags used by "yesod devel" to make compilation faster
flags:
  library-only:
    description: Build for use with "yesod devel"
    manual: false
    default: false
  dev:
    description: Turn on development settings, like auto-reload templates.
    manual: false
    default: false
